### ISSUE TITLE
crash whenever I try to place down item

### ISSUE THREAD

**Issue by DucViet0202** [kiber-pacan/ipla#2]
whenever I try to place down an item the game crash. Here is the log
[crash-2024-10-30_03.58.30-client.txt](https://github.com/user-attachments/files/17563127/crash-2024-10-30_03.58.30-client.txt)

**Comment by kiber-pacan** [comment]
details?

**Comment by DucViet0202** [comment]
[tl-logger15733779253587105951.txt](https://github.com/user-attachments/files/17566784/tl-logger15733779253587105951.

**Comment by DucViet0202** [comment]
[tl-logger15733779253587105951.txt](https://github.com/user-attachments/files/17566792/tl-logger15733779253587105951.txt)

**Comment by kiber-pacan** [comment]
idk what's the problem

**Comment by kiber-pacan** [comment]
> idk what's the problem

too stoopid

**Comment by kiber-pacan** [comment]
can you try again with latest modrinth release?

**Comment by DucViet0202** [comment]
Sorry for the late reply. I think It works now
